name: Agoric SDK save Node.js build
description: 'Set up Node.js environment and restore cached built files'

inputs:
  node-version:
    description: 'The version of Node.js we used'
    required: true

runs:
  using: composite
  steps:
    - name: cache build outputs
      uses: actions/cache@v1
      with:
        path: .
        key: ${{ runner.os }}-${{ inputs.node-version }}-built-${{ github.sha }}
